<div class="page-heading"><div><p class="eyebrow">APPLICATION</p><h1>応募設定</h1></div></div>
<?php if (!$event): ?><section class="panel empty-state"><p>先にイベント設定を作成してください。</p></section><?php else: ?>
<?php $enabled = $submitted === [] ? (bool)$event['application_enabled'] : (bool)$submitted['application_enabled']; $deadline = $submitted['application_deadline_at'] ?? ($event['application_deadline_at'] ? (new DateTimeImmutable($event['application_deadline_at']))->setTimezone(new DateTimeZone($timezone))->format('Y-m-d\TH:i') : ''); $purpose = $submitted['privacy_purpose_text'] ?? ($event['privacy_purpose_text'] ?: $defaultPurpose); $eventEndsAt = (new DateTimeImmutable($event['ends_at']))->setTimezone(new DateTimeZone($timezone))->format('Y年n月j日 H:i'); ?>
<?php if ($errors !== []): ?>
<div class="flash flash-error" role="alert">
    <strong>入力内容にエラーがあります。</strong>
    <span>各項目の赤いメッセージを確認してください。</span>
</div>
<?php endif; ?>
<form class="panel form-grid" method="post"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrfToken,ENT_QUOTES,'UTF-8') ?>"><fieldset class="wide"><legend>応募機能</legend><label class="checkbox"><input type="checkbox" name="application_enabled" value="1" <?= $enabled?'checked':'' ?>>応募を受け付ける</label></fieldset><label>応募締切<span>空欄の場合はイベント終了日時</span><input type="datetime-local" name="application_deadline_at" value="<?= htmlspecialchars($deadline,ENT_QUOTES,'UTF-8') ?>"><?php if(isset($errors['application_deadline_at'])):?><small class="field-error"><?= htmlspecialchars($errors['application_deadline_at'],ENT_QUOTES,'UTF-8') ?></small><?php endif;?></label><div class="deadline-reference"><span>イベント終了日時</span><strong><?= htmlspecialchars($eventEndsAt,ENT_QUOTES,'UTF-8') ?></strong></div><label class="wide">個人情報の利用目的<textarea name="privacy_purpose_text" maxlength="2000" rows="5"><?= htmlspecialchars($purpose,ENT_QUOTES,'UTF-8') ?></textarea><?php if(isset($errors['privacy_purpose_text'])):?><small class="field-error"><?= htmlspecialchars($errors['privacy_purpose_text'],ENT_QUOTES,'UTF-8') ?></small><?php endif;?></label><fieldset class="wide"><legend>応募項目</legend><?php foreach($fields as $field):?><?php $type=$field['field_type']; $current=$submitted['fields'][$type]??['enabled'=>(bool)$field['is_enabled'],'required'=>(bool)$field['is_required']]; ?><label><?= ['name'=>'氏名','email'=>'メールアドレス','address'=>'住所','phone'=>'電話番号'][$type] ?><select name="field_<?= $type ?>"><option value="disabled" <?= !$current['enabled']?'selected':'' ?>>使用しない</option><option value="optional" <?= $current['enabled']&&!$current['required']?'selected':'' ?>>任意</option><option value="required" <?= $current['required']?'selected':'' ?>>必須</option></select></label><?php endforeach;?><?php if(isset($errors['fields'])):?><p class="field-error"><?= htmlspecialchars($errors['fields'],ENT_QUOTES,'UTF-8') ?></p><?php endif;?></fieldset><div class="wide"><button>応募設定を保存</button></div></form><?php endif;?>
