<div class="page-heading"><div><p class="eyebrow">EVENT</p><h1>イベント設定</h1></div></div>
<?php require dirname(__DIR__) . '/form-error-summary.php'; ?>
<form class="panel form-grid" method="post" action="<?= htmlspecialchars($url('admin/event'), ENT_QUOTES, 'UTF-8') ?>">
    <input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrfToken, ENT_QUOTES, 'UTF-8') ?>">
    <label class="wide">イベント名<span>必須・100文字以内</span><input name="name" maxlength="100" required value="<?= htmlspecialchars((string) $values['name'], ENT_QUOTES, 'UTF-8') ?>"><?php if (isset($errors['name'])): ?><small class="field-error"><?= htmlspecialchars($errors['name'], ENT_QUOTES, 'UTF-8') ?></small><?php endif; ?></label>
    <label>開始日時<input type="datetime-local" name="starts_at" required value="<?= htmlspecialchars((string) $values['starts_at'], ENT_QUOTES, 'UTF-8') ?>"><?php if (isset($errors['starts_at'])): ?><small class="field-error"><?= htmlspecialchars($errors['starts_at'], ENT_QUOTES, 'UTF-8') ?></small><?php endif; ?></label>
    <label>終了日時<input type="datetime-local" name="ends_at" required value="<?= htmlspecialchars((string) $values['ends_at'], ENT_QUOTES, 'UTF-8') ?>"><?php if (isset($errors['ends_at'])): ?><small class="field-error"><?= htmlspecialchars($errors['ends_at'], ENT_QUOTES, 'UTF-8') ?></small><?php endif; ?></label>
    <label>達成に必要なスタンプ数<input type="number" name="required_stamp_count" min="1" max="20" required value="<?= (int) $values['required_stamp_count'] ?>"><?php if (isset($errors['required_stamp_count'])): ?><small class="field-error"><?= htmlspecialchars($errors['required_stamp_count'], ENT_QUOTES, 'UTF-8') ?></small><?php endif; ?></label>
    <label class="wide">説明<textarea name="description" maxlength="2000" rows="5"><?= htmlspecialchars((string) $values['description'], ENT_QUOTES, 'UTF-8') ?></textarea><?php if (isset($errors['description'])): ?><small class="field-error"><?= htmlspecialchars($errors['description'], ENT_QUOTES, 'UTF-8') ?></small><?php endif; ?></label>
    <label class="wide">参加者向け注意事項<textarea name="notice_text" maxlength="1000" rows="4"><?= htmlspecialchars((string) $values['notice_text'], ENT_QUOTES, 'UTF-8') ?></textarea></label>
    <label class="wide">達成時メッセージ<textarea name="completion_message" maxlength="1000" rows="3"><?= htmlspecialchars((string) $values['completion_message'], ENT_QUOTES, 'UTF-8') ?></textarea></label>
    <fieldset class="wide"><legend>緊急時の一時停止</legend><label class="checkbox"><input type="checkbox" name="is_paused" value="1" <?= $values['is_paused'] ? 'checked' : '' ?>>受付を一時停止する</label><label>一時停止中の案内<textarea name="pause_message" maxlength="1000" rows="3"><?= htmlspecialchars((string) $values['pause_message'], ENT_QUOTES, 'UTF-8') ?></textarea><?php if (isset($errors['pause_message'])): ?><small class="field-error"><?= htmlspecialchars($errors['pause_message'], ENT_QUOTES, 'UTF-8') ?></small><?php endif; ?></label></fieldset>
    <div class="wide"><button type="submit"><?= $eventExists ? '変更を保存' : 'イベントを作成' ?></button></div>
</form>
